#!/bin/sh

sudo apt-get update

sudo apt-get install tmux

sudo apt-get install bti irssi ekg2 \
  pal \
  imapfilter mutt notmuch \

# GitHub
sudo apt-get install ruby2.0 ruby2.0-dev
gem install hub bundler

# Python
sudo apt-get install python3.3 \
  python3-pip \
  python3-lxml \
  python3-docutils

sudo pip3 install -r requirements.txt

sudo apt-get install sqlite3
