#!/bin/sh

sudo apt-get update

sudo apt-get install tmux

sudo apt-get install bti irssi ekg2

# GitHub
sudo apt-get install ruby
sudo gem install hub

# Python
sudo apt-get install python3 \
  python-pip python3-pip \
  python-lxml python3-lxml \

sudo pip-3.2 install -r requirements.txt

sudo apt-get install sqlite3
