#!/bin/sh
set -e

if ! test $USER = tlevine; then
  echo Run this as tlevine.
  exit 1
fi

for dir in git safe nsa; do
  su tlevine -c "mkdir ~/$dir"
done

(
  cd git
  git clone safe:git/secrets-home
  mv ~/.ssh /tmp/ssh-bak
  cd
  ln -s git/secrets-home/.ssh .
)
( 
  git clone git@github.com:tlevine/profile.git
)
