#!/bin/sh
set -e

if ! test $USER = root; then
  echo Run this as root.
  exit 1
fi

export PKG_PATH="http://ftp.NetBSD.org/pub/pkgsrc/packages/$(uname -s)/$(uname -m)/$(uname -r|cut -f '1 2' -d.)/All"

binary_pkgs='git-base tmux vim mosh offlineimap mutt python33 wget w3m irssi bash fish'
src_pkgs='wip/ekg2'

# Install binaries
pkgin install $binary_pkgs

# Install from source
for pkg in $src_pkgs; do
  pkg_info $(echo $pkg|cut -d/ -f2) > /dev/null ||
  (
    cd /usr/pkgsrc/$pkg
    make install
  )
done

# Configure users
if ! userinfo tlevine 2> /dev/null; then
  usermod -s /usr/pkg/bin/bash -m tlevine
fi
