#!/bin/sh
set -e

if ! test $USER = root; then
  echo Run this as root.
  exit 1
fi

apt-get update

apt-get install \
  locales \
  tmux pal \
  irssi ekg2 \
  imapfilter mutt notmuch \
  mosh fish

apt-get install python3.3 \
  python3-pip \
  python3-lxml \
  python3-docutils
